### ISSUE TITLE
How  to  make GPSMatrix data.

### ISSUE THREAD

**Issue by ShilangChen1011** [StephenHausler/Multi-Process-Fusion#3]
May I ask how your GPSMatrix is produced? I see only GPS latitude and longitude data on the data set website, are these data all manually calibrated?Is there a special tool?

**Comment by StephenHausler** [comment]
Hi Yike-chen,
I've just added a new file to the repo called "CreateGPSMatFile_OxfordRobotCar.m".
This file gives an example of creating a GPS matrix file from GPS timestamped datafiles (in this case for the Oxford RobotCar dataset). Basically I construct a sparse matrix where '1' corresponds to the reference database match index for the current query image, plus or minus the ground truth tolerance.
